config/routes.rb
Marchapp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'users#new'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save {self.email = email.downcase}
	before_create :create_remember_token

	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
		uniqueness: {case_sensitive: false}

	validates :password, length: {minimum: 6}
	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.hash(User.new_remember_token)
		end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			#sign in user and redirect to show page
			sign_in user
			redirect_back_or user
		else
			#create error message
			flash.now[:error] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy




  def new
  	@user = User.new
  end

  def index
    @users = User.paginate(page:params[:page])
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else 
  		render 'new'
  	end
  end

  def edit
    #@user = User.find(params[:id])
  end

  def update
    #@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      #successful update
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to user_url
  end


  private

  	def user_params
  		params.require(:user).permit(:name,:email,:password,:password_confirmation)
  	end

    #Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash(remember_token))
		self.current_user = user 
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end



	def current_user=(user)	
		@current_user = user
	end

	def current_user
		remember_token = User.hash(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end



	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl, built by MBY
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '#' %></li>
          <li><%= link_to "Help",    '#' %></li>

          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>

          <% else %>
            <li><%= link_to "Sign in", '#' %></li>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>


<body>
	<%= render 'layouts/header' %>

	<% flash.each do |k,v| %>
		<div class="alert alert-<%= k %>"><%= v %></div>
	<% end %>



	<%= yield %>
	<%= debug(params) if Rails.env.development? %>

	<%= render 'layouts/footer' %>
</body>


</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<li>
			<%= link_to user.name, user %>
			<% if current_user.admin? && !current_user?(user) %>
				| <%= link_to "delete", user, method: :delete, data: {confirm: "You sure?"} %>
			<% end %>
		</li>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h2>Sign up</h2>

<p>This is of course Users#new, home of the signup page.</p>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class:"btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>